# Comandos linux



In [1]:
!ls

sample_data


In [2]:
!pwd

/content


In [ ]:
!pip freeze

In [5]:
!pip install numpy

#Importar libreria

In [7]:
import numpy as np

#Convertir lista en arrays de numpy

In [8]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(lista)

list

In [10]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(arr)

numpy.ndarray

#Slicing

In [12]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [13]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

#Tipos de datos en numpy

In [14]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [17]:
arr

array([1, 2, 3, 4])

In [15]:
arr_float = np.array([1,2,3,4],dtype="float64")
arr_float.dtype

dtype('float64')

In [16]:
arr_float

array([1., 2., 3., 4.])

#Cast de tipo de datos

In [19]:
arr = np.array([0,1,2,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [20]:
arr_bool

array([False,  True,  True,  True,  True])

In [22]:
arr_string = arr.astype(np.string_)
arr_string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')