In [2]:
import numpy as np

#Scalar

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#Vector

In [5]:
vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

#Matriz 2 dimensiones

In [7]:
matriz2d = np.array([
    [1,2,3],
    [4,5,6]
])
print(matriz2d)
matriz2d.ndim

[[1 2 3]
 [4 5 6]]


2

#Tensor - N dimensiones

In [8]:
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3