# Generación de datos aleatorios

In [1]:
import numpy as np

# Arange

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [6]:
np.ones((10,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Eye

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace

In [8]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Random

In [9]:
np.random.rand()

0.5311721600929744

In [10]:
np.random.rand(4)

array([0.65142579, 0.77367898, 0.97115596, 0.70904578])

In [11]:
np.random.rand(4,4)

array([[0.34182827, 0.45672212, 0.96556651, 0.36958991],
       [0.1628111 , 0.48428352, 0.57431371, 0.77771678],
       [0.24617692, 0.06221532, 0.78098456, 0.26989508],
       [0.60995634, 0.48440934, 0.04334276, 0.44274325]])

In [12]:
np.random.randint(1,100,(10,10))

array([[48, 32, 23, 88, 54, 97, 49, 84,  3, 66],
       [97, 63, 65, 46, 80, 35,  4, 18, 80, 65],
       [64, 53,  7, 74, 91, 13, 54, 84, 18, 24],
       [ 8,  2, 14, 40, 59, 34, 83, 24, 33, 80],
       [70, 39, 36, 44, 46, 86, 43, 58, 52, 82],
       [10,  3, 80, 87, 84, 66, 71, 94, 71, 41],
       [97, 96, 46, 75, 92, 26, 32, 95, 78, 67],
       [96, 92, 61, 54, 80, 38,  3, 14, 22, 88],
       [40, 32, 93, 79, 55, 60, 91, 35,  1, 19],
       [22, 80, 56,  3, 36, 78, 51, 33, 49,  8]])