# Funciones comunes en numpy

In [1]:
import numpy as np

# Shape y reshape

In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[7, 9],
       [9, 2],
       [8, 6]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [6]:
arr.reshape(1,6)

array([[7, 9, 9, 2, 8, 6]])

In [7]:
arr.ndim

2

# Max y argmax

In [9]:
arr = np.random.randint(1,20,10)
arr

array([13, 14, 18,  2, 10, 13,  8,  8,  8, 11])

In [10]:
matriz = arr.reshape(2,5)
matriz

array([[13, 14, 18,  2, 10],
       [13,  8,  8,  8, 11]])

In [12]:
arr.max()

18

In [13]:
matriz.max()

18

In [14]:
matriz.max(1)

array([18, 13])

In [16]:
arr.argmax()

2

In [17]:
matriz.argmax()

2

# Min y argmin

In [18]:
arr.min()

2

In [19]:
arr.argmin()

3

In [20]:
matriz.min(0)

array([13,  8,  8,  2, 10])

# Sort

In [21]:
arr

array([13, 14, 18,  2, 10, 13,  8,  8,  8, 11])

In [24]:
arr.sort()
arr

array([ 2,  8,  8,  8, 10, 11, 13, 13, 14, 18])

# Median

In [26]:
np.median(arr)

10.5

# Desviacion estandar std

In [27]:
np.std(arr)

4.153311931459037

# Varianza var

In [28]:
np.var(arr)

17.25