In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

# Filtros por condiciones

In [3]:
indices_condiciones = arr > 5
indices_condiciones

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr[indices_condiciones]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [5]:
arr[arr<5]

array([1, 2, 3, 4], dtype=int8)

In [6]:
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [7]:
arr[arr>5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [8]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [10]:
arr_2=arr[arr==99]
arr_2

array([99, 99, 99, 99, 99], dtype=int8)

# Copy

In [11]:
arr = np.linspace(1,10,10,dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [12]:
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [13]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100], dtype=int8)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)